version: '3.8'
services:

  backend:
    build:
      context: ./backend
    ports:
      - "3305:3308"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3309"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mariadb:10.9
    container_name: project-db
    ports:
      - "3310:3307"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: projectdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
